version: "3.8"

services:
  java-calculator:
    restart: always
    build: backend
    environment:
      - DATABASE_URI=jdbc:mariadb://db:3306/void
      - DATABASE_USER=void
      - DATABASE_PASSWORD=343247t9j2494ge9bofndslmok3079giebrnf
    depends_on:
      - db
  
  nginx:
    image: nginx:alpine
    restart: always
    ports: 
      - 127.0.0.1:5007:80
    volumes:
      - ./frontend:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - java-calculator
      
  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=void
      - MARIADB_USER=void
      - MARIADB_PASSWORD=343247t9j2494ge9bofndslmok3079giebrnf
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d/