version: '3'
services:
 web:
   image: php:8.2-apache
   restart: always
   volumes:
    - ./public/:/var/www/html:ro
    - ./private/:/srv/private/:ro
    - ./rewrite.conf:/etc/apache2/conf-enabled/rewrite.conf:ro
   ports:
    - 0.0.0.0:5003:80
