apiVersion: apps/v1
kind: Deployment
metadata:
  name: buffer-intro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buffer-intro-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: buffer-intro-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: buffer-intro-app
        image: ctfkubernetes.azurecr.io/buffer-overflow-introduction-buffer-intro
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: buffer-intro-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: buffer-intro-app
