-- Create users
CREATE USER IF NOT EXISTS 'chal01'@'%' IDENTIFIED BY 'o1rpu9fjiowfh9p713trohj';
CREATE USER IF NOT EXISTS 'chal02'@'%' IDENTIFIED BY '308rhnsdf791g2bonl12ag5';
CREATE USER IF NOT EXISTS 'chal03'@'%' IDENTIFIED BY 'u91473greofkdslm1920keo';
CREATE USER IF NOT EXISTS 'chal04'@'%' IDENTIFIED BY '8041yh3uoenld10g32ep919';
CREATE USER IF NOT EXISTS 'chal05'@'%' IDENTIFIED BY '48fdfp910837grven5d1jh8';

CREATE USER IF NOT EXISTS 'bot'@'%' IDENTIFIED BY 'iuh39grbnkosnjboaspjina';

CREATE DATABASE IF NOT EXISTS chal01;
CREATE DATABASE IF NOT EXISTS chal02;
CREATE DATABASE IF NOT EXISTS chal03;
CREATE DATABASE IF NOT EXISTS chal04;
CREATE DATABASE IF NOT EXISTS chal05;

GRANT SELECT, INSERT, UPDATE, DELETE ON chal01.* TO 'chal01'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON chal02.* TO 'chal02'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON chal03.* TO 'chal03'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON chal04.* TO 'chal04'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON chal05.* TO 'chal05'@'%';

GRANT SELECT, UPDATE ON chal01.* TO 'bot'@'%';
GRANT SELECT, UPDATE ON chal02.* TO 'bot'@'%';
GRANT SELECT, UPDATE ON chal03.* TO 'bot'@'%';
GRANT SELECT, UPDATE ON chal04.* TO 'bot'@'%';
GRANT SELECT, UPDATE ON chal05.* TO 'bot'@'%';
FLUSH PRIVILEGES;