version: '3'
services:
 web:
   build: src
   restart: always
   volumes:
    - ./src/flag.txt:/flag-with-unguessable-name.txt:ro
    - ./src/config:/etc/webmin/config:ro
   ports:
    - "0.0.0.0:10000:10000"
