name: Run CTFd Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    name: Run ctfd.py
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if needed)
        run: pip install -r requirements.txt

      - name: Run ctfd.py
        run: python ctfd.py ./ --token ${{ secrets.CTFD_TOKEN }} --url ${{ secrets.CTFD_URL }}
