name: Run CTFd Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    name: Run ctfd.py
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if needed)
        run: pip install -r requirements.txt

      - name: Find 2nd level directories
        id: find-dirs
        run: |
          changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs -I % dirname % | sort -u)
          echo "Changed directories: $changed_dirs" >> changed-dirs.txt
          echo "::set-output name=dirs::$changed_dirs"
        
      - name: Run ctfd.py in changed directories
        id: run-ctfd
        run: |
          changed_dirs=($(cat changed-dirs.txt))
          for dir in "${changed_dirs[@]}"; do
            echo "Running ctfd.py in $dir"
            python ctfd.py "$dir" --token ${{ secrets.CTFD_TOKEN }} --url ${{ secrets.CTFD_URL }}
          done
        env:
          changed-dirs-file: changed-dirs.txt
