name: Run CTFd Script

on:
  push:
    branches:
      - main

jobs:

  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Update CTFd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Extract the first two levels of the directory structure
            truncated_path=$(echo "$file" | cut -d'/' -f-2)
            echo "$truncated_path was changed"
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if needed)
        run: pip install -r requirements.txt

      - name: Run ctfd.py for each path
        run: |
          for truncated_path in ${{ steps.changed-files.outputs.all_changed_files }}; do
            python ctfd.py "$truncated_path" --token ${{ secrets.CTFD_TOKEN }} --url ${{ secrets.CTFD_URL }}
          done
